name: Deploy nextpath-lp to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy_lp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy LP to Firebase Hosting
        run: firebase deploy --only hosting --project nextpath-lp --config firebase_lp.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_NEXTPATH_LP }}
